<script lang="ts">
	import CodeMirror from 'svelte-codemirror-editor';
	import { javascript } from '@codemirror/lang-javascript';
	import { html } from '@codemirror/lang-html';
	import { css } from '@codemirror/lang-css';
	import { json } from '@codemirror/lang-json';
	import { oneDark } from '@codemirror/theme-one-dark';
	import { EditorView } from '@codemirror/view';
	import Container from './Container.svelte';
	import Spinner from './Spinner.svelte';
	import { getBrowserPodEditorContext } from '../context';
	import { debounce } from '../utils';

	const { fileSysReady, selectedFile, fileContent, browserPodRunning, saveFile } = getBrowserPodEditorContext();

	export let onDocChanged: (() => void) | undefined = undefined;

	let className = '';
	export { className as class };

	function getLanguageExtension(filename: string) {
		const ext = filename.split('.').pop()?.toLowerCase();
		switch (ext) {
			case 'js': case 'mjs': return [javascript()];
			case 'html': case 'svelte': return [html()];
			case 'css': return [css()];
			case 'json': return [json()];
			default: return [];
		}
	}

	const debounceSaveFile = debounce(() => saveFile($selectedFile, $fileContent), 1000);

	$: editorExtensions = [
		...getLanguageExtension($selectedFile),
		oneDark,
		EditorView.updateListener.of((update) => {
			if (update.docChanged) {
				onDocChanged?.();
				if ($browserPodRunning) debounceSaveFile();
			}
		})
	];
</script>

<Container
	title="Editor"
	class={className}
>
	<span slot="headerInline" class="file-path">
		{($selectedFile || '').toUpperCase()}
	</span>
	{#if !$fileSysReady}
		<Spinner />
	{:else}
		<CodeMirror
			class="cm-editor"
			bind:value={$fileContent}
			extensions={editorExtensions}
		/>
	{/if}
</Container>

<style>
	.file-path {
		color: var(--color-primary);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		max-width: 250px;
		font-weight: 600;
		font-size: 0.75rem;
	}

	/* CodeMirror editor styling - uses :global() because these classes are generated by the library */
	:global(.cm-editor) {
		flex: 1;
		height: 100%;
		min-height: 0;
		display: block;
		background: transparent;
		color: var(--editor-text-color);
	}

	:global(.cm-editor .cm-cursor) {
		border-left: 2px solid var(--editor-cursor-color) !important;
	}

	:global(.cm-editor .cm-scroller) {
		overflow: auto;
		height: 100%;
		font-family: var(--editor-font-family);
		font-size: var(--editor-font-size);
		background: transparent;
	}

	:global(.cm-editor .cm-gutters) {
		background: var(--editor-gutter-bg);
		border-right: 1px solid var(--editor-gutter-border);
		color: var(--editor-gutter-text);
	}

	:global(.cm-editor .cm-lineNumbers .cm-gutterElement) {
		color: var(--editor-gutter-text);
		padding: 0 6px 0 3px;
	}

	:global(.cm-editor .cm-activeLine) {
		background: var(--editor-active-line-bg);
	}

	:global(.cm-editor .cm-line) {
		padding: 0 6px 0 3px;
	}

	@media (min-width: 640px) {
		:global(.cm-editor .cm-lineNumbers .cm-gutterElement) {
			padding: 0 8px 0 4px;
		}
		:global(.cm-editor .cm-line) {
			padding: 0 8px 0 4px;
		}
	}
</style>
