<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import CodeMirror from 'svelte-codemirror-editor';
	import { javascript } from '@codemirror/lang-javascript';
	import { html } from '@codemirror/lang-html';
	import { css } from '@codemirror/lang-css';
	import { json } from '@codemirror/lang-json';
	import { oneDark } from '@codemirror/theme-one-dark';
	import { EditorView } from '@codemirror/view';
	import Container from './Container.svelte';
	import Spinner from './Spinner.svelte';
	import { resolveContext } from '../context.ts';
	import { debounce } from '../utils.ts';


	interface Props {
		onDocChanged?: (() => void) | undefined;
		ctxId?: string;
		class?: string;
	}

	let { onDocChanged = undefined, ctxId = undefined, class: className = '' }: Props = $props();

	const { fileSysReady, browserPodRunning, saveFile, loadFile, editors, activeEditorId, registerEditor, unregisterEditor, setActiveEditor } = (() => resolveContext(ctxId))();
	

	// Editor registration
	let editorId: number = $state();
	let content = $state('');
	let loadedFilePath = '';  // Plain variable - not reactive, just tracks last loaded path

	onMount(() => {
		editorId = registerEditor();
	});

	onDestroy(() => {
		if (editorId !== undefined) {
			unregisterEditor(editorId);
		}
	});

	// Track file path for this editor
	let editorConfig = $derived(editorId !== undefined ? $editors.get(editorId) : undefined);
	let filePath = $derived(editorConfig?.filePath ?? '');

	// Load content when file path changes
	$effect(() => {
		if (filePath && $fileSysReady && filePath !== loadedFilePath) {
			loadedFilePath = filePath;
			loadFile(filePath).then(fileContent => {
				content = fileContent;
			}).catch(e => {
				console.error('Failed to load file:', e);
			});
		}
	});

	// Check if this editor is active (only show indicator when multiple editors exist)
	let isActive = $derived($editors.size > 1 && $activeEditorId === editorId);

	function getLanguageExtension(filename: string) {
		const ext = filename.split('.').pop()?.toLowerCase();
		switch (ext) {
			case 'js': case 'mjs': return [javascript()];
			case 'html': case 'svelte': return [html()];
			case 'css': return [css()];
			case 'json': return [json()];
			default: return [];
		}
	}

	const debounceSaveFile = debounce(() => {
		if (loadedFilePath) {
			saveFile(loadedFilePath, content);
		}
	}, 1000);

	let editorExtensions = $derived([
		...getLanguageExtension(filePath),
		oneDark,
		EditorView.updateListener.of((update) => {
			if (update.docChanged) {
				onDocChanged?.();
				if ($browserPodRunning) debounceSaveFile();
			}
		})
	]);

	function handleFocus() {
		if (editorId !== undefined) {
			setActiveEditor(editorId);
		}
	}
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
	class="editor-wrapper"
	class:editor-active={isActive}
	onclick={handleFocus}
	onfocusin={handleFocus}
>
	<Container
		title="Editor"
		class={className}
	>
		{#snippet headerInline()}
				<span  class="file-path">
				{(filePath || '')}
			</span>
			{/snippet}
		{#if !$fileSysReady}
			<Spinner />
		{:else}
			<CodeMirror
				class="cm-editor"
				bind:value={content}
				extensions={editorExtensions}
			/>
		{/if}
	</Container>
</div>

<style>
	.editor-wrapper {
		display: flex;
		flex-direction: column;
		flex: 1;
		min-height: 0;
		min-width: 0;
	}

	.editor-wrapper.editor-active {
		outline: var(--bpe-editor-active-border, 2px solid var(--bpe-color-primary));
		outline-offset: -2px;
	}

	.file-path {
		color: var(--bpe-color-text);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		max-width: 250px;
		font-weight: 500;
		font-size: 0.75rem;
	}

	/* CodeMirror editor styling - uses :global() because these classes are generated by the library */
	:global(.cm-editor) {
		flex: 1;
		height: 100%;
		min-height: 0;
		display: block;
		background: transparent;
		color: var(--bpe-editor-text-color);
	}

	:global(.cm-editor .cm-cursor) {
		border-left: 2px solid var(--bpe-editor-cursor-color) !important;
	}

	:global(.cm-editor .cm-scroller) {
		overflow: auto;
		height: 100%;
		font-family: var(--bpe-editor-font-family);
		font-size: var(--bpe-editor-font-size);
		background: transparent;
	}

	:global(.cm-editor .cm-gutters) {
		background: var(--bpe-editor-gutter-bg);
		border-right: 1px solid var(--bpe-editor-gutter-border);
		color: var(--bpe-editor-gutter-text);
	}

	:global(.cm-editor .cm-lineNumbers .cm-gutterElement) {
		color: var(--bpe-editor-gutter-text);
		padding: 0 6px 0 3px;
	}

	:global(.cm-editor .cm-activeLine) {
		background: var(--bpe-editor-active-line-bg);
	}

	:global(.cm-editor .cm-line) {
		padding: 0 6px 0 3px;
	}

	@media (min-width: 640px) {
		:global(.cm-editor .cm-lineNumbers .cm-gutterElement) {
			padding: 0 8px 0 4px;
		}
		:global(.cm-editor .cm-line) {
			padding: 0 8px 0 4px;
		}
	}
</style>
